services:
  postgres-user:
    image: postgres:16
    container_name: user_postgres
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5434:5432"
    networks:
      - ecommerce-network

  postgres-product:
    image: postgres:16
    container_name: product_postgres
    environment:
      POSTGRES_DB: product_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5435:5432"
    networks:
      - ecommerce-network

  postgres-order:
    image: postgres:16
    container_name: order_postgres
    environment:
      POSTGRES_DB: order_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5436:5432"
    networks:
      - ecommerce-network

  postgres-payment:
    image: postgres:16
    container_name: payment_postgres
    environment:
      POSTGRES_DB: payment_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5437:5432"
    networks:
      - ecommerce-network

  redis:
    image: redis:7-alpine
    container_name: ecommerce_redis
    ports:
      - "6380:6379"
    networks:
      - ecommerce-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - ecommerce-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - ecommerce-network

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - ecommerce-network

  eureka-server:
    image: steeltoeoss/eureka-server
    container_name: eureka_server
    ports:
      - "8761:8761"
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge