spring:
  application:
    name: user-service
  cloud:
    compatibility-verifier:
      enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5434/user_db?TimeZone=UTC
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    url: jdbc:postgresql://localhost:5434/user_db?TimeZone=UTC
    user: postgres
    password: 12345

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
    fetch-registry: false

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  access-token-expiry: 900000
  refresh-token-expiry: 604800000

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics